### ISSUE TITLE
Many of the functions are useless or have redundant code

### ISSUE THREAD

**Issue by gregzakh** [jdhitsolutions/PSScriptTools#76]
For example, `Get-PowerShellEngine`. It's so strange why you accomplish this via `Get-Process` instead `Get-Command`.

```powershell
gcm (('powershell','pwsh')[$PSVersionTable.PSVersion.Major -ge 6])
```
Want to more info? Just add piped `fl *` in the end. Or you can add next into your $PSProfile:

```powershell
Add-Member -InputObject $PSVersionTable -Name PSEngine -Value (
   gcm (('powershell','pwsh')[$PSVersionTable.PSVersion.Major -ge 6])
).FileVersionInfo -MemberType NoteProperty
```
After:

```powershell
$PSVersionTable.PSEngine # profit!
```

`Get-ModuleCommand` is just awful wrapper for `Get-Module`. Code can be reduced to oneliner.
And so on...

**Comment by jdhitsolutions** [comment]
I think you are missing the point. Yes, there are many things you can easily do at the console, provided you have enough experience. The functions in this module are meant to make it easier for people to achieve certain tasks. Yes, many are wrappers.  But often I'm adding extra value. For example, the `Get-PowerShellEngine` function is using `Get-Process`  because the function can write a custom detailed object to the pipeline. Sure, someone could take the extra steps you take, but if you want a repeatable, easy to use command you write a function. If the module doesn't meet your needs then by all means don't use it.

**Comment by gregzakh** [comment]
The sacred meaning of the wrappers is out of my comprehansion. Given that cmdlets are also a kind of wrappers (over .NET types), wrappers over wrappers are anything else than over-engineering. OK, maybe you are right and people tend to use wrappers instead creating original things. But which the truelly goal of this module? To do simple things more coplicated, doesn't it?

**Comment by jdhitsolutions** [comment]
You are correct that PowerShell is based on an abstraction to make things easier to use. That is what I have done here. I've created tools that abstract what I thought might be useful tasks. Sure, you could use the .NET Framework to get the current date and time.  But that assumes you know .NET. Whereas, someone completely new can be taught to find commands and use help to see how to use Get-Date. Plus Get-Date adds additional features. That's all I'm doing here. If you are happy banging out all the PowerShell you need, then go right ahead.  You are not the intended group for this module.

**Comment by gregzakh** [comment]
Some sort of sophistry. From the side it looks like you are submitting your code as an indispensable, kind of cool stuff. Has thirty years in the IT industry been wasted for you? Ahh, Jeff?

**Comment by lanwench** [comment]
@gregzakh , my stars, if you don't like the !@#$% code, don't use it. Nobody is forcing you! Github issues are intended to help people address things that don't work. It isn't a forum for rude jerks who want to insult people who are offering _free tools_ to help strangers on the internet. If you prefer alternate methods, please feel free to go far away and use them. Godspeed.

**Comment by gregzakh** [comment]
> @gregzakh , my stars, if you don't like the !@#$% code, don't use it. Nobody is forcing you! Github issues are intended to help people address things that don't work. It isn't a forum for rude jerks who want to insult people who are offering _free tools_ to help strangers on the internet. If you prefer alternate methods, please feel free to go far away and use them. Godspeed.

I see everything in perfect order with your self-criticism, since you call yourself a rude jerk. It’s not clear why you call Jeff so. By the way, Jeff is already an adult boy, able to fend for himself and not needing "mother's" care. This is the first. Secondly, the essence of the conversation is to save the module from redundant code and not produce wrappers over the wrappers, as it is unprofessional and can mislead inexperienced people that suppose the true purpose of the pwsh is creating wrappers. More than once I came across a similar attitude when giving lectures on pwsh (and after all the PowerShell's community are surprised at why powershell will not get into the top of popular languages). In general, before throwing a tantrum, you would think about the essence of things. Thirdly, we are not personally acquainted with you (what not to say about Jeff), so it's not up to you to judge ethics.

**Comment by jdhitsolutions** [comment]
I think we're done here. I have more pressing issues on my mind these days and this discussion has long moved on from being constructive. I'll stick with my internationally recognized expertise and deep experience. You are entitled to your own opinion about how to use PowerShell. But since there isn't a technical problem with any code, there is no reason for this issue to remain open.
