### ISSUE TITLE
[Question] New-PSFormatXML

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#78]
Is it possible to wrap lines in Table view?

Also I tried to understand how to hide table headers in Table view using this cmdlet. Can you show me? There is HideTableHeaders parameter for table view.
Thanks.

**Comment by scriptingstudio** [comment]
Thanks for a hint

**Comment by jdhitsolutions** [comment]
Re-opening  because I'll use this issue as an enhancement to add a Wrap parameter to `New-PSFormatXML`.

**Comment by jdhitsolutions** [comment]
I added a `Wrap` parameter to the command in v2.23.0.

**Comment by scriptingstudio** [comment]
It does work. Perfect. How did I live without it? It eliminates using intermediate variables and format-table which kills objects.

**Comment by scriptingstudio** [comment]
There are 2 identical lines
```
$li    = $doc.createNode("element", "ListItem", $null)
```
Is it right?

**Comment by jdhitsolutions** [comment]
Looks like a copy and paste goof. It doesn't have any negative effects.

**Comment by scriptingstudio** [comment]
Also it is time to replace obsolescent and slow `New-Object` with `[typename]::new()`

**Comment by jdhitsolutions** [comment]
I wouldn't say that `New-Object` is obsolete. I prefer to use cmdlets wherever possible because people who view the code can look at help for `New-Object`. Plus, cmdlets often offer additional features that you don't get by calling a .NET method directly. And in terms of performance, yes the `New()` method is faster. By 3ms. I could see where this might make a difference at scale. But this command is probably only going to create 1 file at a time so the performance gain is insignificant.
